dashboard/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from tasks import views as task_views
from django.conf import settings
from dashboard import views

urlpatterns = [
    path('tasks/', include('tasks.urls')),
    path('admin/', admin.site.urls),
    path('social/', include('social_django.urls', namespace='social')),
    url('login/', auth_views.LoginView.as_view(), name='login'),
    url('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('add_task/', task_views.add_task, name='add_task'),
    path('', views.home, name='index'),
]

tasks/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'tasks'
urlpatterns = [
    path('', views.SummaryView.as_view(), name='index'),
    path('list/', views.TaskListView.as_view(), name='list'),
    path('add_task/', views.add_task, name='add_task'),
    path('check_off/', views.check_off, name='check_off'),
    path('uncheck/', views.uncheck, name='uncheck'),
    #path('delete_task', views.delete_task, name='delete_task'),
    #url(r'^sort_tasks/*', views.sort_tasks, name='sort_tasks'),
    path('delete_task/', views.delete_task, name='delete_task'),
    path('edit_task/', views.edit_task, name='edit_task'),
    path('add_category/', views.add_category, name='add_category'),
    path('delete_category/', views.delete_category, name='delete_category'),
    path('filter_tasks/', views.filter_tasks, name='filter_tasks'),
    path('archive_finished/', views.archive_finished, name='archive_finished'),
    path('stats/', views.StatsView.as_view(), name='stats'),
    path('calendar/', views.CalendarView.as_view(), name='calendar'),
    path('archive_task/', views.archive_task, name='archive_task'),
    path('check_archived/', views.checkbox_archived, name='check_archived'),
    path('as_csv', views.as_csv, name='as_csv'),
    path('move_date_backward/', views.move_date_backward, name='move_date_backward'),
    path('move_date_forward/', views.move_date_forward, name='move_date_forward'),
]

tasks/models.py
from django.db import models
import datetime


# Create your models here.

class ShowArchived(models.Model):
    user = models.IntegerField(default=-1, primary_key=True)
    show_archived = models.BooleanField('archived', default=False)


class Task(models.Model):
    user = models.IntegerField(default=-1)
    task_name = models.CharField(max_length=200)
    task_desc = models.CharField(max_length=400)
    end_time = models.DateTimeField('end time')
    length = models.DurationField('length', default=datetime.timedelta(hours=3), null=True, blank=True)
    hours = models.IntegerField('hours', default=2)
    minutes = models.IntegerField('minutes', default=0)
    completed = models.BooleanField('completed')
    date_completed = models.DateField('date_completed', null=True)
    archived = models.BooleanField('archived', default=False)
    link = models.URLField(default="")
    HOMEWORK = 'Homework'
    CHORE = 'Chore'
    WORK = 'Work'
    ERRAND = 'Errand'
    LIFESTYLE = 'Life'
    OTHERS = 'Other'
    CATEGORIES = [
        (HOMEWORK, 'Homework'),
        (CHORE, 'Chore'),
        (WORK, 'Work'),
        (ERRAND, 'Errand'),
        (LIFESTYLE, 'Lifestyle'),
        (OTHERS, 'Others'),
    ]
    category = models.CharField(
        null=True,
        blank=True,
        choices=CATEGORIES,
        max_length=32,
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.task_name

    @property
    def get_html_url(self):
        # url = reverse('tasks:task_edit', args=(self.id))
        # return f'<p>{self.task_name}</p><a href="{url}">edit</a>'
        return f'<p>{self.task_name}</p><a href="#">edit</a>'


class Category(models.Model):
    name = models.CharField(max_length=32)
    user = models.IntegerField()

tasks/forms.py
from django import forms
from .models import Task
import bootstrap_datepicker_plus


class TaskForm(forms.Form):
    # Reformats the html input to work with the django datetime field
    attempt = ['%Y-%m-%d %H:%M:%S',  # '2006-10-25 14:30:59'
               '%Y-%m-%d %H:%M',  # '2006-10-25 14:30'
               '%Y-%m-%d',  # '2006-10-25'
               '%m/%d/%Y %H:%M:%S',  # '10/25/2006 14:30:59'
               '%m/%d/%Y %H:%M',  # '10/25/2006 14:30'
               '%m/%d/%Y',  # '10/25/2006'
               '%m/%d/%y %H:%M:%S',  # '10/25/06 14:30:59'
               '%m/%d/%y %H:%M',  # '10/25/06 14:30'
               '%m/%d/%y',
               '%Y-%m-%dT%H:%M']  # '10/25/06'
    task_name = forms.CharField(label='Task Name', max_length=100, required=False)
    task_desc = forms.CharField(label='Task Description', max_length=200, required=False)
    end_time = forms.DateTimeField(label='End Time', input_formats=attempt, widget=bootstrap_datepicker_plus.DateTimePickerInput(format=attempt[1]), required=False)
    hours = forms.IntegerField(label='Estimated Length (Hours)', required=False)
    minutes = forms.IntegerField(label='Estimated Length (Minutes)', required=False)
    category = forms.Select(choices=Task.CATEGORIES)


class FilterForm(forms.Form):
    filter_key = forms.CharField(label='Filter Key', max_length=100)

tasks/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Count, F, Min, Sum, Avg
from django.db.models.functions import Cast, Extract
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls import reverse
from django.views import generic
from djqscsv import render_to_csv_response
from django.views.generic import TemplateView, ListView
from django.core.exceptions import ObjectDoesNotExist

from .forms import TaskForm, FilterForm
from .models import Task, Category, ShowArchived
import datetime
from graphos.renderers.gchart import LineChart, PieChart
from graphos.sources.model import SimpleDataSource
from django.db.models import DateField
from django.utils import safestring
from .utils import Calendar
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from urllib.parse import urlparse
from math import floor


def remove_omitted_fields():
    omitted_fields = set(
        ['id', 'user', 'created_at', 'completed', 'archived', 'date_completed', 'length', 'end_time', 'hours',
         'minutes'])
    l = []
    for field in Task._meta.get_fields():
        val = field.name
        # if(val == 'task_desc'):
        #    val = 'task_description'
        if val in omitted_fields:
            continue
        elif '_' in val:
            l.append((val.replace('_', ' '), val))
            continue
        else:
            l.append((val, val))
    return l


class SummaryView(generic.ListView):
    model = Task
    template_name = 'tasks/landing.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        task_list = Task.objects.filter(user=self.request.user.id, completed=False, archived=False,
                                        end_time__gte=datetime.datetime.now())
        task_list = task_list.order_by('end_time')
        d = get_date(self.request.GET.get('day', None))
        cal = Calendar(d.year, d.month)
        for week in cal.monthdayscalendar(cal.year, cal.month):
            if week[0] <= datetime.datetime.now().day <= week[week.__len__() - 1]:
                curr_week = week
        start_of_week = datetime.datetime.today() - datetime.timedelta(
            days=datetime.datetime.today().isoweekday() % 7)
        tasks_left_this_week = Task.objects.filter(user=self.request.user.id, completed=False,
                                                            end_time__gte=start_of_week,
                                                            end_time__lte=start_of_week + datetime.timedelta(days=6)
                                                            )
        estimated_hours = tasks_left_this_week.aggregate(total=Sum('hours'))['total']
        estimated_minutes = tasks_left_this_week.aggregate(total=Sum('minutes'))['total']
        if estimated_minutes and estimated_hours:
            estimated_hours += estimated_minutes // 60
            estimated_minutes %= 60
        else:
            estimated_hours = 0
            estimated_minutes = 0
        task_list = task_list[:5]
        html_cal = cal.formatmonth(withyear=True, weekonly=True, user=self.request.user.id)
        context['task_list'] = task_list
        context['calendar'] = safestring.mark_safe(html_cal)
        context['tasks_left'] = tasks_left_this_week.count()
        context['est_hours'] = estimated_hours
        context['est_minutes'] = estimated_minutes
        context['state'] = Task.objects.filter(user=self.request.user.id, completed=True,
                                               date_completed__gte=start_of_week,
                                               date_completed__lte=start_of_week + datetime.timedelta(days=6)
                                               ).count()
        return context


# Create your views here.
class TaskListView(generic.ListView):
    """
    Used to display the current tasks the user has assigned
    """
    template_name = 'tasks/task_list.html'
    context_object_name = 'task_list'

    def get_queryset(self):
        sort_key = self.request.GET.get('sort_by', 'give-default-value')

        """
        show_arch is used to determine whether to filter out archived tasks
        If current user does not have ShowArchived model, make one
        """
        show_arch = False
        try:
            if self.request.user.is_authenticated:
                show_arch = ShowArchived.objects.get(user=self.request.user.id).show_archived
            else:
                return render(self.request, 'tasks/login.html')
        except:
            sa = ShowArchived()
            # sa.show_archived = False;
            sa.user = self.request.user.id
            sa.save()

        if sort_key != 'give-default-value' and not show_arch:
            return Task.objects.filter(user=self.request.user.id, archived=False).order_by(sort_key, 'created_at')
        elif sort_key != 'give-default-value' and show_arch:
            return Task.objects.filter(user=self.request.user.id).order_by(sort_key, 'created_at')
        elif sort_key == 'give-default-value' and not show_arch:
            return Task.objects.filter(user=self.request.user.id, archived=False).order_by('end_time', 'created_at')
        else:
            return Task.objects.filter(user=self.request.user.id).order_by('end_time', 'created_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['fields'] = remove_omitted_fields()
        if self.request.user.is_authenticated:
            context['sa'] = ShowArchived.objects.get(user=self.request.user.id)
        return context


@login_required
def add_task(request):
    """
    Used to add a task to the personal dashboard
    :param request: The form posting from the add_task.html page
    :return: A redirect depending on whether or not the input was good
    """
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            t = Task()
            t.user = request.POST.get('user')
            t.task_name = request.POST.get('task_name')
            t.task_desc = request.POST.get('task_desc')
            t.end_time = request.POST.get('end_time')
            t.hours = request.POST.get('hours')
            t.minutes = request.POST.get('minutes')
            t.category = request.POST.get('category')
            t.link = request.POST.get('link', "")
            # Ensure that the start dates are correct
            if not t.task_name:
                return render(request, 'tasks/add_task.html',
                              {'form': form,
                               'error_message': "Task name is required!", })
            elif not t.end_time:
                return render(request, 'tasks/add_task.html',
                              {'form': form,
                               'error_message': "Due Date is required!", })
            elif t.end_time < str(datetime.datetime.now()):
                return render(request, 'tasks/add_task.html',
                              {'form': form, 'error_message': "Due date must be later than current time.", })
            elif not t.hours or not t.minutes:
                return render(request, 'tasks/add_task.html',
                              {'form': form,
                               'error_message': "Estimated time is required! Please enter valid time values: (Hours >= 0 and 0 <= Min <= 59)", })
            elif int(t.minutes) < 0 or int(t.minutes) >= 60 or int(t.hours) < 0:
                return render(request, 'tasks/add_task.html',
                              {'form': form,
                               'error_message': "Please enter valid time values! (Hours >= 0 and 0 <= Min <= 59)", })
            else:
                t.completed = False
                t.save()
                if request.POST.get('repeat') == 'once':
                    multiplier = 0
                elif request.POST.get('repeat') == 'weekly':
                    multiplier = 1
                elif request.POST.get('repeat') == 'monthly':
                    multiplier = 4
                elif request.POST.get('repeat') == 'annually':
                    multiplier = 52
                for i in range(1, int(request.POST.get('times')) + 1):
                    curr_t = Task()
                    curr_t.task_name = request.POST.get('task_name')
                    curr_t.task_desc = request.POST.get('task_desc')
                    curr_t.category = request.POST.get('category')
                    curr_t.end_time = datetime.datetime.strptime(t.end_time, '%Y-%m-%dT%H:%M') + datetime.timedelta(
                        weeks=i * multiplier)
                    curr_t.hours = request.POST.get('hours')
                    curr_t.minutes = request.POST.get('minutes')
                    curr_t.user = request.POST.get('user')
                    curr_t.completed = False
                    curr_t.link = request.POST.get('link', "")
                    curr_t.save()
                return HttpResponseRedirect(reverse('tasks:list'))
        else:
            return render(request, 'tasks/add_task.html',
                          {'form': form,
                           'error_message': "An unknown error has occurred. Try again", })
    else:
        form = TaskForm()
    return render(request, 'tasks/add_task.html', {'form': form})


def edit_task(request):
    if (request.method == 'POST'):
        try:
            task_id = request.GET.get('task_id')
        except:
            return HttpResponseRedirect(reverse('tasks:list'))
        form = TaskForm(request.POST)
        if form.is_valid():
            # t = Task()
            t = Task.objects.get(id=task_id)
            t.user = request.POST.get('user')
            t.task_name = request.POST.get('task_name')
            t.task_desc = request.POST.get('task_desc')
            t.end_time = request.POST.get('end_time')

tasks/templates/tasks/add_task.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap4 %}       {# import bootstrap4/bootstrap3 #}
{% bootstrap_css %}         {# Embed Bootstrap CSS #}
{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
{{ form.media }}
<hr>

<div class="container-md">
    <h3 class="display-4"><u><b>Add New Task</b></u></h3>
    {% if error_message %}<p><font color="red"><strong>{{ error_message }}</strong></font></p>{% endif %}
    <form action="{% url 'tasks:add_task' %}" method='post'>
    {% csrf_token %}
        <input type="hidden" value="{{user.id}}" id="user" name="user">
        <div class="form-group">
            <label for="{{ form.task_name.name }}"><b>Task Name</b></label>
            <input class="form-control" type="text" id="{{ form.task_name.name }}" name="{{ form.task_name.name }}">
        </div>
        <div class="form-group">
            <label><b>Due Date</b></label>
            {{ form.end_time }}
        </div>
        <div class="form-group form-row">
            <div class="col">
                <label><b>Estimated Length</b></label>
            </div>
            <div class="col">
                <input class="form-control" type="number" id="{{ form.hours.name }}" name="{{ form.hours.name }}" placeholder="Hours">
            </div>
            <div class="col text-left">
                <p class="lead">hr</p>
            </div>
            <div class="col">
                <input class="form-control" type="number" id="{{ form.minutes.name }}" name="{{ form.minutes.name }}" placeholder="Minutes">
            </div>
            <div class="col text-left">
                <p class="lead">min</p>
            </div>
        </div>
        <div class="form-group">
            <label for="category"><b>Category</b></label>
            <select name="category" id="category" class="custom-select">
            {% for choice in form.category.choices %}
                <option value="{{ choice.0 }}">{{ choice.1 }}</option>
            {% endfor %}
            </select>

        </div>
        <div class="form-group">
            <label for="{{ form.task_desc.name }}"><b>Task Description</b> (<i>*Optional*</i>)</label>
            <input class="form-control" type="text" id="{{ form.task_desc.name }}" name="{{ form.task_desc.name }}" value="">
        </div>
        <div class="form-group">
            <label for="link"><b>Link</b> (<i>*Optional*</i>)</label>
            <input class="form-control" type="url" id="link" name="link" value="">
        </div>

        <div class = "form-group form-row">
            <div class="col">
                <label><b>Repeat Task 'X' Times</b> (<i>*Optional*</i>) </label>
                 <input class = "form-control" type="number" min="0" value="0" name="times" id="times" required> </input>
            </div>
            <div class="col">
                 <label for="repeat"> <b>With The Below Frequency</b>  (<i>*Optional*</i>)</label>
                <select name = "frequency" id="repeat" class="custom-select">
                    <option value="once">Add Task</option>
                    <option value="weekly">Add Task Weekly</option>
                    <option value="monthly">Add Task Monthly</option>
                    <option value="annually">Add Task Annually</option>
                </select>
            </div>
        </div>

        <div class="form-group" style="text-align: right;">
            <button class="btn btn-primary" type="submit">
                Submit
            </button>
        </div>

        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endif %}
    </form>
</div>
<hr>
{% endblock %}

tasks/templates/tasks/landing.html
{% extends 'base.html' %}
{% block content %}


<div class = "flex-container" >
    <center><h2><b><i>Welcome, {{user.username}}! Let's get started:</i></b></h2></center>
    <hr>
    <div class = "task-list">
        {% if task_list|length >= 5 %}
            <h3>Next 5 Tasks: </h3>
        {% elif task_list|length > 1 %}
            <h3>Next {{ task_list|length }} Tasks: </h3>
        {% elif task_list|length == 1 %}
            <h3>Last Task: </h3>
        {% else %}
            <h3>You have 0 future tasks.</h3>
        {% endif %}
        {% if task_list %}
        <div class="list-group list-group-flush">
            <!-- Individual Tasks -->
            {% for task in task_list %}
                {% if not task.completed %}
                    <li class="list-group-item">
                {% else %}
                    <li class="list-group-item" style="background-color: #80ff80;">
                {% endif %}
                    <div class="d-flex">
                        <div class="widget-content-left">
                            <!-- Checkbox form: Credit to Henry -->
                            {% if not task.completed %}
                                <form action="{% url 'tasks:check_off' %}" method='post' id="check_{{ task.id }}">
                                    {% csrf_token %}
                                    <input type="hidden" name="task_id" value='{{task.id}}'>
                                    <!--<input class="form-check-input" type="checkbox"
                                    onclick="document.getElementById('check_{{ task.id }}').submit();">-->
                                    <div class="custom-checkbox custom-control">
                                        <input class="custom-control-input" type="checkbox" id="_{{ task.id }}"
                                               onclick="document.getElementById('check_{{ task.id }}').submit();">
                                        <label class="custom-control-label" for="_{{ task.id }}">
                                            <h5 class="widget-heading" style="padding-right: 10px;">
                                            {% if task.link == '' %}
                                                {{ task.task_name }}
                                            {% else %}
                                                <a href="{{ task.link }}">{{ task.task_name }}</a>
                                            {% endif %}

                                            {% if task.category == 'Homework' %}
                                                <div class="badge badge-primary ml-2">{{ task.category }}</div>
                                            {% elif task.category == 'Chore' %}
                                                <div class="badge badge-warning ml-2">{{ task.category }}</div>
                                            {% elif task.category == 'Work' %}
                                                <div class="badge badge-danger ml-2">{{ task.category }}</div>
                                            {% elif task.category == 'Errand' %}
                                               <div class="badge badge-info ml-2">{{ task.category }}</div>
                                            {% elif task.category == 'Life' %}
                                                <div class="badge badge-success ml-2">{{ task.category }}</div>
                                            {% elif task.category == 'Other' %}
                                                <div class="badge badge-secondary ml-2">{{ task.category }}</div>
                                            {% else %}
                                                <div class="badge badge-light ml-2">Category</div>
                                            {% endif %}
                                            </h5>
                                        </label>
                                    </div>
                                </form>
                            {% else %}
                                <form action="{% url 'tasks:uncheck' %}" method='post' id="uncheck_{{ task.id }}">
                                    {% csrf_token %}
                                    <input type="hidden" name="task_id" value='{{task.id}}'>
                                    <div class="custom-checkbox custom-control">
                                        <input class="custom-control-input" type="checkbox" id="__{{ task.id }}"
                                               onclick="document.getElementById('uncheck_{{ task.id }}').submit();" checked>
                                        <label class="custom-control-label" for="__{{ task.id }}">
                                            <h5 class="widget-heading" style="text-decoration: line-through;">
                                            {% if task.link == '' %}
                                                {{ task.task_name }}
                                            {% else %}
                                                <a href="{{ task.link }}">{{ task.task_name }}</a>
                                            {% endif %}

                                            {% if task.category == 'Homework' %}
                                                <div class="badge badge-primary ml-2" style="text-decoration: line-through;">{{ task.category }}</div>
                                            {% elif task.category == 'Chore' %}
                                                <div class="badge badge-warning ml-2" style="text-decoration: line-through;">{{ task.category }}</div>
                                            {% elif task.category == 'Work' %}
                                                <div class="badge badge-danger ml-2" style="text-decoration: line-through;">{{ task.category }}</div>
                                            {% elif task.category == 'Errand' %}
                                               <div class="badge badge-info ml-2" style="text-decoration: line-through;">{{ task.category }}</div>
                                            {% elif task.category == 'Life' %}
                                                <div class="badge badge-success ml-2" style="text-decoration: line-through;">{{ task.category }}</div>
                                            {% elif task.category == 'Other' %}
                                                <div class="badge badge-secondary ml-2" style="text-decoration: line-through;">{{ task.category }}</div>
                                            {% else %}
                                                <div class="badge badge-light ml-2" style="text-decoration: line-through;">Category</div>
                                            {% endif %}
                                            </h5>
    <!--                                        <h5 class="widget-heading" style="color:green">COMPLETE!</h5>-->
                                        </label>
                                    </div>

                                </form>
                            <script>
                                function undoButton(button) {
                                    document.getElementById(button.id).innerHTML = "Undo?";
                                    document.getElementById(button.id).style = "color:red";
                                }
                                function normalButton(button) {
                                    document.getElementById(button.id).innerHTML = "Completed!";
                                    document.getElementById(button.id).style = "color:green";
                                }
                            </script>

                            {% endif %}
                            <!-- End of Henry's form -->
                        </div>
                        <div class="ml-auto">
                            <div class="d-flex">
                                <div class="ml-auto">
                                    <form action="{% url 'tasks:edit_task' %}" method='get' id="edit_{{ task.id }}">
                                        <input type="hidden" name="task_id" value="{{task.id}}">
                                        <button class="border-0 btn-transition btn btn-outline-success" data-toggle="tooltip" title="Edit"
                                                onclick="document.getElementId('edit_{{ task.id }}').submit();">
                                            <i class="fa fa-edit"></i> </button>
                                    </form>
                                </div>
                                <div class="ml-auto">
                                    <form action="{% url 'tasks:archive_task' %}" method='post' id="archive_{{ task.id }}">
                                        {% csrf_token %}
                                        <input type="hidden" name="task_id" value="{{task.id}}">
                                        <button class="border-0 btn-transition btn btn-outline-warning" data-toggle="tooltip" title="Archive"
                                                onclick="document.getElementId('archive_{{ task.id }}').submit();">
                                            <i class="fa fa-archive"></i> </button>
                                    </form>
                                </div>
                                <div class="ml-auto">
                                    <form action="{% url 'tasks:delete_task' %}" method='post' id="delete_{{ task.id }}">
                                        {% csrf_token %}
                                        <input type="hidden" name="task_id" value="{{task.id}}">
                                        <button class="border-0 btn-transition btn btn-outline-danger" data-toggle="tooltip" title="Delete"
                                                onclick="document.getElementId('delete_{{ task.id }}').submit();">
                                            <i class="fa fa-trash"></i> </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% if not task.completed %}
                        <div class="widget-heading"><b><i>DUE:</i> {{ task.end_time }}</b></div>
                    {% else %}
                        <div class="widget-heading" style="text-decoration: line-through;"><b><i>DUE:</i> {{ task.end_time }}</b></div>
                    {% endif %}
                    <div class="todo-indicator bg-warning"></div>
                </li>
            {% endfor %}
            <!-- End task -->
        </div>
        {% else %}
            <p><a href="{% url 'tasks:add_task' %}">Click here to add a new one!</a></p>
        {% endif %}
    </div>
</div>
<hr>
<div class = "flex-container">
    <h4>Stats Summary: </h4>
    <div class = "stats">
        <div class = "boxed">
            <ul class="list-group list-group-flush">
                <li class="list-group-item lead">
                    Tasks Left This Week: <b>{{tasks_left}}</b>
                </li>
                <li class="list-group-item lead">
                    Estimated Time Required: <b>{{est_hours}} <i>hours</i> {{est_minutes}} <i>minutes</i></b>
                </li>
                <li class="list-group-item lead">
                    {% load static %}
                    Tasks Completed This Week: <b>{{state}}</b>
                </li>
            </ul>
        </div>

    </div>
</div>
<div class="row justify-content-center">
    <div class = "container col-md-8" style="padding: 0px;">
        {{ calendar }}
    </div>
</div>
{% endblock %}

tasks/templates/tasks/login.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<center>
<p><font size="36">
    Please login
    </font>
    <br>
    <font size="36"> :(</font>
</p>
    </center>
{% endblock %}