dashboard/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from tasks import views as task_views
from django.conf import settings
from dashboard import views

urlpatterns = [
    path('tasks/', include('tasks.urls')),
    path('admin/', admin.site.urls),
    path('social/', include('social_django.urls', namespace='social')),
    url('login/', auth_views.LoginView.as_view(), name='login'),
    url('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('add_task/', task_views.add_task, name='add_task'),
    path('', views.home, name='index'),
]

tasks/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'tasks'
urlpatterns = [
    path('', views.SummaryView.as_view(), name='index'),
    path('list/', views.TaskListView.as_view(), name='list'),
    path('add_task/', views.add_task, name='add_task'),
    path('check_off/', views.check_off, name='check_off'),
    path('uncheck/', views.uncheck, name='uncheck'),
    #path('delete_task', views.delete_task, name='delete_task'),
    #url(r'^sort_tasks/*', views.sort_tasks, name='sort_tasks'),
    path('delete_task/', views.delete_task, name='delete_task'),
    path('edit_task/', views.edit_task, name='edit_task'),
    path('add_category/', views.add_category, name='add_category'),
    path('delete_category/', views.delete_category, name='delete_category'),
    path('filter_tasks/', views.filter_tasks, name='filter_tasks'),
    path('archive_finished/', views.archive_finished, name='archive_finished'),
    path('stats/', views.StatsView.as_view(), name='stats'),
    path('calendar/', views.CalendarView.as_view(), name='calendar'),
    path('archive_task/', views.archive_task, name='archive_task'),
    path('check_archived/', views.checkbox_archived, name='check_archived'),
    path('as_csv', views.as_csv, name='as_csv'),
    path('move_date_backward/', views.move_date_backward, name='move_date_backward'),
    path('move_date_forward/', views.move_date_forward, name='move_date_forward'),
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <link rel="icon" href="{% static 'tasks/transparent logo.png' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css">
    <title>Dashboard</title>
  </head>
  <body style="padding-bottom:80px">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="height: 60px; padding-left: 8px;">
<!--        <a class="navbar-brand" href="" style="padding-left: 15px;">Dashboard </a> &lt;!&ndash;Change href to base page or something&ndash;&gt;-->
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav" style="padding-top: 10px; padding-left: 0px;">
            {% if request.user.is_authenticated %}
                <style>
                    img {
                        padding-bottom: 10px;
                        width: 75px;
                        height: auto;
                        opacity: 0.50;
                    }
                    img:hover {
                        opacity: 1;
                    }
                </style>
                 <a class="nav-item nav-link" href="{% url 'index' %}"><img src="{% static 'tasks/transparent logo.png' %}"></a>
                 <div class="navbar-nav" style="padding-top: 7px; padding-left: 5px;">
                     <a class="nav-item nav-link" href="{% url 'tasks:index' %}">Home</a>
                     <a class="nav-item nav-link" href="{% url 'tasks:add_task' %}">Add Task<span class="sr-only"></span></a> <!--change all hrefs-->
                     <a class="nav-item nav-link" href="{% url 'tasks:list' %}">Task List</a>
                     <a class="nav-item nav-link" href="{% url 'tasks:stats' %}">Statistics</a>
                     <a class="nav-item nav-link" href="{% url 'tasks:calendar' %}">Calendar</a>
                 </div>
            {% endif %}
            </div>
        </div>
        <div>
          {% if user.is_authenticated %}
          <a class="text-white">Logged in as: &nbsp{{user.username}}&nbsp</a>
          <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
          {% else %}
          <a class="btn btn-primary" href="{% url 'social:begin' 'google-oauth2' %}" role = "button">Login</a>
        {% endif %}
        </div>  
        <!--<a href="/admin"><button class="btn btn-danger my-2 my-sm-0" type="submit">Admin Settings</button></a>-->
    </nav>
    <div class="Dashboard">
      <style>
        .Dashboard
        {
          margin: 0 auto;
          max-width: 100%;
          
        }
      </style>
      <div class="row justify-content-center">
        <div class="col-md-8">
          <!--<h1 class="mt-2">Django Practice</h1>-->
            <hr class="mt-0 mb-4">
            {% block content %}
            {% endblock %}
        </div>
      </div>
    </div>
    <div class="footer-spacer"></div>
    <div class="container-fluid" style="padding: 0px;">
    <footer class="page-footer font-small blue pt-1 bg-dark my-sticky-footer fixed-bottom" >
      <style>
          .centered {
              position: absolute;
              top: 50%;
              left: 50%;
              transform: translate(-50%, -50%);
              padding: 0px;
              white-space: nowrap;
          }
      </style>
      <div class="container text-center">
        <div class="centered">
            <span class="font-weight-light" style="color: #999999">
                Created by team WILDCARD!: Andrew Boyd, Henry Carscadden, Jimmy Chiou, Ashwin Pathi, Gabriel Simmons
            </span>
        </div>
        <hr>
      </div>
    </footer>
  </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/bootstrap-select.min.js"></script>

    <!-- (Optional) Latest compiled and minified JavaScript translation files -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/i18n/defaults-*.min.js"></script>
  </body>
</html>

templates/home.html
<!doctype html>
{% load static %}
<!--<style>
    .cover-container.d-flex.w-100.h-100.p-34.mx-auto.flex-column{
        background-image: url('/static/tasks/transparent logo.png');
    }
</style>-->
<style>
    img {
      margin-left: auto;
      margin-right: auto;
      opacity: 0.30;
    }
    .centered {
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      padding: 0px;
      white-space: nowrap;
    }
    .cover-container.d-flex.w-100.h-100.p-34.mx-auto.flex-column {
      margin-left: auto;
      margin-right: auto;
      padding-left: 0px;
      padding-right: 0px;
    }
</style>
<html lang="en">
  <head>
    <link rel="icon" href="{% static 'tasks/transparent logo.png'%}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/cover.css' %}">
  </head>

  <body class="text-center">

    <div class="cover-container d-flex w-100 h-100 p-34 mx-auto flex-column">
      <header class="masthead mb-auto">
        <div class="inner">
        </div>
      </header>
      <div class="container-fluid" style="position: relative; padding: 0px;">
        <img class="img-fluid rounded" src="{% static 'tasks/transparent logo.png' %}" alt="logo">
        <div class="centered">
          <h1 class="display-4" style="font-weight: bold;">PROJECT WILDCARD:</h1>
          <h1>The easy way to get stuff done!</h1>
        </div>
      </div>

      <main role="main" class="inner cover" style="padding-top: 8px;" >
        <!--<h1 class="cover-heading">Be Productive!</h1>-->
        <p class="lead">Welcome to <b><i><font color="#17a2b8">Project Wildcard</font></i></b>, a companion for your browser, dedicated to keeping track of and organizing your day.</p>
        <p class="lead">
          <!--<a href="#" class="btn btn-lg btn-danger">Login</a>-->
          {% if user.is_authenticated %}
            <p>Logged in as {{ user.username }}</p>
            <a class="btn btn-danger btn-lg" href="{% url 'logout' %}">Logout</a>
            <a class="btn btn-primary btn-lg" href="{% url 'tasks:index' %}">Dashboard</a>
          {% else %}
            <!--<p class="lead">Login with your Google Account to get started.</p>-->
            <a class="btn btn-primary btn-lg" href="{% url 'social:begin' 'google-oauth2' %}" role = "button">Login with your Google Account to get started</a>
          {% endif %}
        </p>
      </main>

      <footer class="mastfoot mt-auto">
        <div class="inner"> <!--style="white-space: nowrap;">-->
          <span class="text-muted font-weight-light">Team WILDCARD!: Andrew Boyd, Henry Carscadden, Jimmy Chiou, Ashwin Pathi, Gabriel Simmons</span>
        </div>
      </footer>
    </div>
  </body>
</html>

templates/new_home.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/cover.css' %}">
  </head>

  <body class="text-center">

    <div class="cover-container d-flex w-100 h-100 p-34 mx-auto flex-column">
      <header class="masthead mb-auto">
        <div class="inner">
          <h3 class="masthead-brand">Wildcard!</h3>
          <nav class="nav nav-masthead justify-content-center">
            <!-- <a class="nav-link active" href="#">Home</a>
            <a class="nav-link" href="#">Features</a> -->
            <a class="nav-link" href="#">about</a>
          </nav>
        </div>
      </header>

      <main role="main" class="inner cover">
        <h1 class="cover-heading">Be Productive!</h1>
        <p class="lead">Welcome to Wildcard!, a companion for your browser, dedicated of keeping track of and organizing your day.</p>
        <p class="lead">
          <!--<a href="#" class="btn btn-lg btn-danger">Login</a>-->
          {% if user.is_authenticated %}
            <p>Logged as {{ user.username }}</p>
            <a class="btn btn-danger btn-lg" href="{% url 'logout' %}">Logout</a>
          {% else %}
            <p class="lead">Login with your Google Account to get started.</p>
            <a class="btn btn-primary btn-lg" href="{% url 'social:begin' 'google-oauth2' %}" role = "button">Login</a>
          {% endif %}
        </p>
      </main>

      <footer class="mastfoot mt-auto">
        <div class="inner">
          <span class="text-muted font-weight-light">Created by team WILDCARD!: Andrew Boyd, Henry Carscadden, Jimmy Chiou, Ashwin Pathi, Gabriel Simmons</span>
        </div>
      </footer>
    </div>
  </body>
</html>

templates/old_home.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/logo.css' %}">
<hr>
<div class="container">
  <!--<style>font-size: 30; font-style: bold;</style>-->
  <img class="img-fluid rounded" src="{% static 'tasks/Wildcard logo.png' %}" alt="Wildcard" style="width:80%;"></img>
</div>
<hr>
<div class="jumbotron">
  <h1 class="display-4">Be Productive!</h1>
  <p class="lead">Welcome to Dashboard, a companion for your browser, dedicated to keeping track of your day.</p>
  <hr>
    {% if user.is_authenticated %}
      <p>Logged as {{ user.username }}</p>
      <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
    {% else %}
      <p>Login with your Google Account to get started.</p>
      <a class="btn btn-primary" href="{% url 'social:begin' 'google-oauth2' %}" role = "button">Login</a>
    {% endif %}
</div>
<hr>
{% endblock %}